services:
  helper_bot:
    container_name: tgdiscord_bot
    image: tgdiscord_image
    build: 
      context: .
    env_file:
      - .env
    enviroment:
      BOT_TOKEN: "${BOT_TOKEN}"
    depends_on:
      - helper_bot_database

  helper_bot_database:
      container_name: postgres_database_tgdiscord
      image: postgres:16
      volumes:
       - postgres_data:/data/postgres
      ports:
       {5423:5232}
      enviroment:
       PGDATA: /data/postgres
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    profiles:
      - "dev"
    restart: on-failure 
    env_file:
      - .env
    ports:
      - "5050:80"
    volumes:
      -pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:






    

    

        